# This is a basic workflow to help you get started with Actions

name: db-server


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
  workflow_dispatch:


jobs:
  public:
    runs-on: self-host
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
