# This is a basic workflow to help you get started with Actions

name: db-server


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
  workflow_dispatch:


jobs:
  connect:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Disk
        run: |
           ls
        
